spring:
  datasource:
    url: jdbc:h2:mem:starwarsdb
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api
  error:
    include-message: always